export const GET_USERS_LIST_REQUEST = "GET_USERS_LIST_REQUEST";
export const GET_USERS_LIST_SUCCESS = "GET_USERS_LIST_SUCCESS";
export const GET_USERS_LIST_FAIL = "GET_USERS_LIST_FAIL";

export const GET_POSTS_LIST_REQUEST = "GET_POSTS_LIST_REQUEST";
export const GET_POSTS_LIST_SUCCESS = "GET_POSTS_LIST_SUCCESS";
export const GET_POSTS_LIST_FAIL = "GET_POSTS_LIST_FAIL";
